---
title: "Estimated Gene Tree Analyses"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(patchwork)
library(cowplot)
library(tidymodels)  # coord_obs_pred()
library(reshape2)
library(scales)
theme_set(theme_bw())

base_dir <- "../"
estgt_dir <- paste0(base_dir, "est-gts/")
df <- read.csv(paste0(estgt_dir, "analysis/approx_normalized_errors.csv")) %>%
#df <- read.csv(paste0(estgt_dir, "data/out.csv")) %>%
  filter(ntaxa != 30) %>%
    mutate(
        retic_diff = as.factor(nretic_true - nretic_est),
        input_error = min_unrooted_nj_hwcd + sum_constraint_hwcd,
        ngt_label = paste0(ngt, " gene trees"),
        ils_label = factor(
          paste0(str_to_title(ils), " ILS"),
          levels = c("Low ILS", "Med ILS", "High ILS", "Very High ILS")
        ),
        m_label = paste0("m = ", m),
        ils_m_label = paste0("m = ", m, " ", ils_label),
        ntaxa_label = factor(
            paste0(ntaxa, " taxa"),
            levels = paste0(sort(unique(ntaxa)), " taxa")
        ),
        error_diff = unrooted_hwcd - input_error,
        min_greedy_error_diff = unrooted_min_greedy_hwcd - input_error,
        scaled_hwcd = unrooted_hwcd / ntaxa,
        scaled_input_error = input_error / ntaxa,
        scaled_error_diff = scaled_hwcd - scaled_input_error,
        min_greedy_approx_norm_hwcd = if_else(min_greedy_approx_norm_hwcd < unrooted_hwcd,
                                              min_greedy_approx_norm_hwcd, unrooted_hwcd)
    )
nrow(df)
```


## What percect of input error comes from constraints?

```{r}
df %>%
  group_by(ngt_label, ils_m_label, ntaxa_label) %>%
  summarise(
    pct_constraint = sum(sum_constraint_hwcd) / sum(input_error),
    pct_nj = sum(min_unrooted_nj_hwcd) / sum(input_error)
  ) %>%
  melt() %>%
  ggplot(aes(x = ngt_label, y = value, fill = variable)) +
    geom_bar(stat="identity", position="stack") +
    facet_grid(ils_m_label ~ ntaxa_label) +
    labs(title = "Percent error for each input type")

df %>%
  group_by(ngt_label, ils_m_label, ntaxa_label) %>%
  summarise(
    sum_constraint = mean(sum_constraint_hwcd),
    sum_nj = mean(min_unrooted_nj_hwcd)
  ) %>%
  melt() %>%
  ggplot(aes(x = ngt_label, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(ntaxa_label ~ ils_m_label, scales = "free")

pdf("~/temp.pdf", width=8, height=5)
df %>%
  group_by(ngt_label, ils_m_label, ntaxa_label) %>%
  summarise(
    sum_constraint = mean(sum_constraint_hwcd),
    sum_nj = mean(min_unrooted_nj_hwcd)
  ) %>%
  melt() %>%
  ggplot(aes(x = ngt_label, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(ntaxa_label ~ ils_m_label, scales = "free")
dev.off()
```


## Output error vs. Input error

```{r}
p1 <- df %>%
  filter(ntaxa <= 200) %>%
  mutate(
    x = approx_norm_input_hwcd,
    y = approx_norm_hwcd
  ) %>%
  rowwise() %>%
  mutate(x = max(0.01, x), y = max(0.01, y)) %>%
  filter(m == 10) %>%
  ggplot(aes(x = x, y = y, color = ils_label)) +
  facet_grid(ngt_label ~ ntaxa_label) +
  geom_jitter(size=1, alpha=0.7) +
  geom_abline(slope = 1, intercept = 0, color = "black", 
    linetype = "dashed", alpha = 0.5) +
  labs(x = "Normalized Input Error", y = "Normalized Output Error", title = "(a) m = 10") +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  #scale_x_log10() + scale_y_log10() +
  scale_x_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  scale_y_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  coord_obs_pred()
p1

p2 <- df %>%
  filter(ntaxa <= 200) %>%
  mutate(
    #x = if_else(approx_norm_input_hwcd == 0, min_val, ll(approx_norm_input_hwcd)),
    #y = if_else(approx_norm_hwcd == 0, min_val, ll(approx_norm_hwcd))
    x = approx_norm_input_hwcd,
    y = approx_norm_hwcd
  ) %>%
  rowwise() %>%
  mutate(x = max(0.01, x), y = max(0.01, y)) %>%
  filter(m == 20) %>%
  ggplot(aes(x = x, y = y, color = ils_label)) +
  facet_grid(ngt_label ~ ntaxa_label) +
  geom_jitter(size=1, alpha=0.7) +
  geom_abline(slope = 1, intercept = 0, color = "black", 
    linetype = "dashed", alpha = 0.5) +
  labs(x = "Normalized Input Error", y = "", title = "(b) m = 20") +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  #scale_x_log10() + scale_y_log10() +
  scale_x_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  scale_y_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  coord_obs_pred()
p2

(p1 | p2) + plot_layout(guides = "collect", axes = "collect", axis_titles = "collect") & theme(legend.position = "right")

pdf("fig/log-input-vs-output.pdf", width = 10, height = 5)
(p1 | p2) + plot_layout(guides = "collect", axes = "collect", axis_titles = "collect") & theme(legend.position = "right")
dev.off()
```


```{r}

df %>%
  ggplot(aes(x = input_error, y = unrooted_min_greedy_hwcd, shape = ils_label, color = as.factor(m))) +
  facet_grid(ntaxa_label ~ ngt_label) +
  geom_jitter(size=1, alpha=0.7) +
  geom_abline(slope = 1, intercept = 0, color = "black", 
    linetype = "dashed", alpha = 0.5) +
  labs(x = "Input Error", y = "Output Error", title = "m = 10") +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  coord_obs_pred()

df %>%
  ggplot(aes(x = input_error, y = unrooted_min_greedy_hwcd, shape = ils_label, color = as.factor(m))) +
  geom_jitter(size=1, alpha=0.7) +
  geom_abline(slope = 1, intercept = 0, color = "black", 
    linetype = "dashed", alpha = 0.5) +
  labs(x = "Input Error", y = "Output Error", title = "m = 10") +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  coord_obs_pred()

df %>%
  ggplot(aes(x = approx_norm_input_hwcd, y = min_greedy_approx_norm_hwcd, shape = ils_label, color = as.factor(m))) +
  geom_jitter(size=1, alpha=0.7) +
  geom_abline(slope = 1, intercept = 0, color = "black", 
    linetype = "dashed", alpha = 0.5) +
  labs(x = "Input Error", y = "Output Error", title = "m = 10") +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  coord_obs_pred() +
  scale_shape_manual(values = c(3, 1))

df %>%
  ggplot(aes(y = min_greedy_approx_norm_hwcd - approx_norm_input_hwcd, x = m_label, fill = ngt_label)) +
  geom_violin() +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
  scale_fill_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a"))
df %>%
  ggplot(aes(y = min_greedy_approx_norm_hwcd - approx_norm_input_hwcd, x = m_label, fill = ngt_label)) +
  geom_boxplot() +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
  scale_fill_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a"))

```


# Output error

```{r}
p <- df %>%
  filter(ntaxa <= 200) %>%
  ggplot(aes(y = min_greedy_approx_norm_hwcd, x = m_label, fill = factor(ngt))) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
  labs(
    x = "", y = "Output Error"
  ) +
  scale_fill_manual("Gene trees", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a"))
p

pdf("fig/normalized-hwcd.pdf", width=8, height=4)
p
dev.off()
```


# Error vs. nretics

```{r}
pdf("fig/hwcd-vs-nretic.pdf", width = 8, height = 4)
df %>%
  filter(m == 20 & ntaxa < 1000) %>%
  #group_by(ntaxa_label, m_label, ngt_label, ils_label, nretic_true) %>%
  #mutate(
  #  avg_hwcd = mean(min_greedy_approx_norm_hwcd),
  #  low_hwcd = quantile(min_greedy_approx_norm_hwcd, 0.05),
  #  high_hwcd = quantile(min_greedy_approx_norm_hwcd, 0.95)
  #) %>%
  ggplot(aes(y = min_greedy_approx_norm_hwcd, x = nretic_true, color = ngt_label)) +
  geom_jitter(width = 0.25, alpha = 0.15) +
  geom_smooth(method = NULL, se = FALSE, span = 0.75) +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
  labs(
    x = "Number of Reticulations", y = "Output Error"
  ) +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a"))
dev.off()
```

```{r}
p <- df %>%
  filter(m == 20 & ntaxa <= 200) %>%
  group_by(ntaxa_label, m_label, ngt_label, ils_label, nretic_true) %>%
  summarise(
    avg_hwcd = mean(min_greedy_approx_norm_hwcd),
    low_hwcd = quantile(min_greedy_approx_norm_hwcd, 0.05),
    high_hwcd = quantile(min_greedy_approx_norm_hwcd, 0.95)
  ) %>%
  ggplot(aes(x = nretic_true, y = avg_hwcd, color = ngt_label)) +
  geom_point(alpha = 0.25) +
  geom_line() +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  labs(x = "Number of Reticulations", y = "Average Normalized Output Error")
p

pdf("fig/hwcd-vs-nretic.pdf", width = 8, height = 4)
p
dev.off()
```

# Out vs. in w/ retics

```{r}
medians <- df %>%
  group_by(nretic_true, ngt_label, ngt, ntaxa_label, ils_label) %>%
  summarise(
    med = median(approx_norm_hwcd)
  ) %>%
  ungroup()

p <- df %>%
  filter(ntaxa < 1000) %>%
  ggplot(aes(x = nretic_true, y = approx_norm_hwcd, color = factor(ngt))) +
  geom_jitter(width = 0.4, height = 0.0, alpha = 0.15) +
  geom_smooth(data = medians, aes(x = nretic_true, y = med, color = factor(ngt)), method = "lm", formula = y ~ x, se = F, linewidth = 1) +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
  scale_color_manual("Gene trees", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  labs(x = "Reticulations", y = "Normalized HWCD")
p

pdf("fig/error-vs-nretic.pdf", width=8, height=4)
p
dev.off()
```


## Estimated Reticulations

```{r}
before_df <- df %>%
  group_by(ntaxa_label, ils_label, m_label, ngt_label) %>%
  summarise(y = mean(approx_norm_hwcd)) %>%
  mutate(uq_id = paste0(ntaxa_label, " ", ils_label, " ", m_label, " ", ngt_label)) %>%
  mutate(x = 1)
after_df <- df %>%
  group_by(ntaxa_label, ils_label, m_label, ngt_label) %>%
  summarise(y = mean(min_greedy_approx_norm_hwcd)) %>%
  mutate(uq_id = paste0(ntaxa_label, " ", ils_label, " ", m_label, " ", ngt_label)) %>%
  mutate(x = 2)

rbind(before_df, after_df) %>%
  ggplot(aes(x = x, y = y, group = uq_id)) +
  geom_point() +
  geom_line() +
  facet_grid(ils_label ~ ntaxa_label)
```


# Number of Reticulations

```{r}
df %>%
  group_by(ntaxa_label, rep) %>%
  summarise(nretic = mean(nretic_true)) %>%
  ggplot(aes(x = nretic, group = as.factor(ntaxa_label), fill = as.factor(ntaxa_label))) +
    geom_density(alpha = 0.5) +
    scale_fill_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
    scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
    labs(x = "Number of Reticulations")


df %>%
  group_by(ntaxa_label, rep) %>%
  summarise(nretic = mean(nretic_true)) %>%
  ggplot(aes(x = nretic, group = as.factor(ntaxa_label), group = as.factor(ntaxa_label), fill = as.factor(ntaxa_label))) +
    geom_histogram(position = "identity", alpha = 1) +
    scale_fill_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
    scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
    labs(x = "Number of Reticulations")
```



# GTEE

```{r}
gtee_df <- read.csv("/mnt/dv/wid/projects4/SolisLemus-network-merging/InPhyNet-Simulations/est-gts/analysis/gtee.csv")
gtee_df
```

```{r}
summary(gtee_df$avg_gtee)
```

```{r}
gtee_df %>%
  ggplot(aes(x = avg_gtee, y = norm_output_error, color = factor(ils))) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0) +
  facet_grid(ntaxa ~ m) +
  coord_obs_pred()
```




# Big combined HWCD figure

```{r}
dummy_guide <- function(
    labels = NULL,  
    ..., 
    title = NULL, 
    key   = draw_key_point,
    guide_args = list()
) {
  # Capture arguments
  aesthetics <- list(...)
  n <- max(lengths(aesthetics), 0)
  labels <- labels %||%  seq_len(n)
  
  # Overrule the alpha = 0 that we use to hide the points
  aesthetics$alpha <- aesthetics$alpha %||% rep(1, n)
  
  # Construct guide
  guide_args$override.aes <- guide_args$override.aes %||% aesthetics
  guide <- do.call(guide_legend, guide_args)
  
  # Allow dummy aesthetic
  update_geom_defaults("point", list(dummy = "x"))
  
  dummy_geom <- geom_point(
    data = data.frame(x = rep(Inf, n), y = rep(Inf, n), 
                      dummy = factor(labels)),
    aes(x, y, dummy = dummy), alpha = 0, key_glyph = key
  )
  dummy_scale <- discrete_scale(
    "dummy", "dummy_scale", palette = scales::identity_pal(), name = title,
    guide = guide
  )
  list(dummy_geom, dummy_scale)
}


medians <- df %>%
  filter(ntaxa > 30 & ntaxa < 1000) %>%
  group_by(nretic_true, ngt_label, ngt, ntaxa_label, ils_label) %>%
  summarise(
    med = median(approx_norm_hwcd)
  ) %>%
  ungroup()


p1 <- df %>%
  filter(ntaxa <= 200) %>%
  ggplot(aes(y = min_greedy_approx_norm_hwcd, x = m_label, fill = factor(ngt))) +
#  ggplot(aes(y = min_greedy_approx_norm_hwcd, x = m_label, fill = ils_label)) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
#  facet_grid(ngt_label ~ ntaxa_label, scales = "free") +
  labs(
    x = "", y = "Normalized HWCD"
  ) +
  scale_fill_manual("Gene trees", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  ggtitle("A")
p1

p2 <- df %>%
  filter(ntaxa <= 200) %>%
  mutate(
    x = approx_norm_input_hwcd,
    y = approx_norm_hwcd
  ) %>%
  rowwise() %>%
  mutate(x = max(0.01, x), y = max(0.01, y)) %>%
  filter(m == 20) %>%
#  ggplot(aes(x = x, y = y, color = ils_label)) +
#  facet_grid(ngt_label ~ ntaxa_label) +
  ggplot(aes(x = x, y = y, color = ngt_label)) +
  facet_grid(ils_label ~ ntaxa_label) +
  geom_jitter(size=1, alpha=0.7) +
  geom_abline(slope = 1, intercept = 0, color = "black", 
    linetype = "dashed", alpha = 0.5) +
  labs(x = "Normalized Input Error", y = "") +
  scale_color_manual("", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  scale_x_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  scale_y_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  ggtitle("B") +
  guides(fill = "none")
p2

p_top <- (p1 + p2) + plot_layout(guides = "collect", axes = "collect")
p_top

p1
p2

p_left <- (p1 / p2)
p_left
```


```{r}

df1 <- split_df %>%
  mutate(approx_norm_hwcd = normalized_hwcd) %>%
  select(c(method, approx_norm_hwcd, ils, ntaxa, rep))

df2 <- snaq_df %>%
  mutate(
    method = if_else(m == 10, "mnet10", if_else(m == 20, "mnet20", "snaq"))
  ) %>%
  select(c(method, approx_norm_hwcd, ils, ntaxa, rep))

combined_other_method_df <- rbind(df1, df2) %>%
  mutate(ils = paste0(str_to_title(ils), " ILS")) %>%
  mutate(
    method = factor(
      method,
      levels = c("consensus", "neighbor", "mnet10", "mnet20", "snaq")
    )
  )

p3 <- combined_other_method_df %>%
  filter(ntaxa != 30) %>%
  #ggplot(aes(x = ils, y = approx_norm_hwcd, fill = method)) +
  ggplot(aes(x = method, fill = ils, y = approx_norm_hwcd)) +
  geom_boxplot() +
  scale_y_continuous(
    "Normalized HWCD",
    limits = c(0, 1)
  ) +
  scale_x_discrete(
    "Method",
    labels = c(
      "consensus" = "Consensus Network",
      "neighbor" = "NeighborNet",
      "mnet10" = "InPhyNet m=10",
      "mnet20" = "InPhyNet m=20",
      "snaq" = "SNaQ"
    )
  ) +
  labs(x = "") +
  ggtitle("C")

p4 <- combined_other_method_df %>%
  filter(ntaxa == 30) %>%
  #ggplot(aes(x = ils, fill = method, y = approx_norm_hwcd)) +
  ggplot(aes(x = method, y = approx_norm_hwcd, fill = ils)) +
  geom_boxplot() +
  scale_y_continuous(
    "",
    limits = c(0, 0.3)
  ) +
  labs(x = "") +
  scale_x_discrete(
    "Method",
    labels = c(
      "consensus" = "Consensus Network",
      "neighbor" = "NeighborNet",
      "mnet10" = "InPhyNet m=10",
      "mnet20" = "InPhyNet m=20",
      "snaq" = "SNaQ"
    )
  ) +
  ggtitle("D") &
  guides(fill = "none")
p4

p_bottom <- (p3 + p4) + plot_layout(guides = "collect") &
#  scale_fill_manual(
#    "Method",
#    values = c(
#      "mnet10" = '#7570b3',
#      "mnet20" = "#e7298a",
#      "snaq" = "#66a61e",
#      "consensus" ='#d95f02',
#      "neighbor" = '#1b9e77'
#    ),
#    labels = c(
#      "consensus" = "Consensus Network",
#      "neighbor" = "NeighborNet",
#      "mnet10" = "InPhyNet m=10",
#      "mnet20" = "InPhyNet m=20",
#      "snaq" = "SNaQ"
#    ),
#    breaks = c(
#      "consensus",
#      "neighbor",
#      "mnet10",
#      "mnet20",
#      "snaq"
#    )
#  )
  scale_fill_manual(
    "ILS",
    values = c("Low ILS" = '#7570b3', "High ILS" = "#e7298a")
  )
p_bottom

p_right <- (p3 / p4) + plot_layout(guides = "collect") &
  scale_fill_manual(
    "Method",
    values = c(
      "mnet10" = '#7570b3',
      "mnet20" = "#e7298a",
      "snaq" = "#66a61e",
      "consensus" ='#d95f02',
      "neighbor" = '#1b9e77'
    ),
    labels = c(
      "consensus" = "Consensus Network",
      "neighbor" = "NeighborNet",
      "mnet10" = "InPhyNet m=10",
      "mnet20" = "InPhyNet m=20",
      "snaq" = "SNaQ"
    ),
    breaks = c(
      "consensus",
      "neighbor",
      "mnet10",
      "mnet20",
      "snaq"
    )
  )


key_fig <- combined_other_method_df %>%
  ggplot(aes(x = ils, fill = method, y = approx_norm_hwcd)) +
  geom_boxplot() &
  scale_fill_manual(
    "Method",
    values = c(
      "mnet10" = '#7570b3',
      "mnet20" = "#e7298a",
      "snaq" = "#66a61e",
      "consensus" ='#d95f02',
      "neighbor" = '#1b9e77'
    ),
    labels = c(
      "consensus" = "Consensus Network",
      "neighbor" = "NeighborNet",
      "mnet10" = "InPhyNet m=10",
      "mnet20" = "InPhyNet m=20",
      "snaq" = "SNaQ"
    ),
    breaks = c(
      "consensus",
      "neighbor",
      "mnet10",
      "mnet20",
      "snaq"
    )
  )

(p_top / p_bottom) + plot_layout(
  axes = "collect",
  widths = c(2.2, 1, 1),
  heights = c(1.8, 1, 1)
) +
  plot_layout(tag_level = 'new') &
  theme(plot.tag = element_text(size = 8))
```


```{r}
(p_top / p_bottom) + plot_layout(
  heights = c(4, 4, 1.5, 1.5),
  widths = c(4, 4, 2, 2)
) +
  plot_layout(tag_level = 'new') &
  theme(plot.tag = element_text(size = 8)) &
  guides(color = "none")

pdf("fig/hwcd_combined.pdf", width=12, height=9)
(p_top / p_bottom) + plot_layout(
  heights = c(4, 4, 1.5, 1.5),
  widths = c(4, 4, 2, 2)
) +
  plot_layout(tag_level = 'new') &
  theme(plot.tag = element_text(size = 8)) &
  guides(color = "none")
dev.off()

#pdf("fig/hwcd_combined_key.pdf", width=12, height=10)
#(key_fig + key_fig) / (key_fig + key_fig) + plot_layout(axes = "collect", guides = "collect")
#dev.off()
```






# PNAS figures

```{r}
p3 <- combined_other_method_df %>%
  filter(ntaxa != 30) %>%
  #ggplot(aes(x = ils, y = approx_norm_hwcd, fill = method)) +
  ggplot(aes(x = method, fill = ils, y = approx_norm_hwcd)) +
  geom_boxplot() +
  scale_y_continuous(
    "Normalized HWCD",
    limits = c(0, 1)
  ) +
  scale_x_discrete(
    "Method",
    labels = c(
      "consensus" = "Consensus Network",
      "neighbor" = "NeighborNet",
      "mnet10" = "InPhyNet m=10",
      "mnet20" = "InPhyNet m=20",
      "snaq" = "SNaQ"
    )
  ) +
  labs(x = "") +
  ggtitle("A")

p4 <- combined_other_method_df %>%
  filter(ntaxa == 30) %>%
  filter(ils == "Low ILS") %>%
  #ggplot(aes(x = ils, fill = method, y = approx_norm_hwcd)) +
  ggplot(aes(x = method, y = approx_norm_hwcd, fill = ils)) +
  geom_boxplot() +
  scale_y_continuous(
    "",
    limits = c(0, 0.3)
  ) +
  labs(x = "") +
  scale_x_discrete(
    "Method",
    labels = c(
      "consensus" = "Consensus Network",
      "neighbor" = "NeighborNet",
      "mnet10" = "InPhyNet m=10",
      "mnet20" = "InPhyNet m=20",
      "snaq" = "SNaQ"
    )
  ) +
  ggtitle("B") &
  guides(fill = "none")
p4
p <- (p3 + p4) + plot_layout(guides = "collect") &
  scale_fill_manual(
    "ILS",
    values = c("Low ILS" = '#7570b3', "High ILS" = "#e7298a")
  )
p

pdf("pnas_fig/hwcd-other-methods.pdf", width = 11.4, height = 11.4/3)
p
dev.off()
```



```{r}

p1 <- df %>%
  filter(ntaxa <= 200) %>%
  ggplot(aes(y = min_greedy_approx_norm_hwcd, x = m_label, fill = factor(ngt))) +
#  ggplot(aes(y = min_greedy_approx_norm_hwcd, x = m_label, fill = ils_label)) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(ils_label ~ ntaxa_label, scales = "free") +
#  facet_grid(ngt_label ~ ntaxa_label, scales = "free") +
  labs(
    x = "", y = "Normalized HWCD"
  ) +
  scale_fill_manual("Gene trees", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  ggtitle("A")
p1

p2 <- df %>%
  filter(ntaxa <= 200) %>%
  mutate(
    x = approx_norm_input_hwcd,
    y = approx_norm_hwcd
  ) %>%
  rowwise() %>%
  mutate(x = max(0.01, x), y = max(0.01, y)) %>%
  filter(m == 20) %>%
#  ggplot(aes(x = x, y = y, color = ils_label)) +
#  facet_grid(ngt_label ~ ntaxa_label) +
  ggplot(aes(x = x, y = y, color = ngt_label)) +
  facet_grid(ils_label ~ ntaxa_label) +
  geom_jitter(size=1, alpha=0.7) +
  geom_abline(slope = 1, intercept = 0, color = "black", 
    linetype = "dashed", alpha = 0.5) +
  labs(x = "Normalized Input Error", y = "") +
  scale_color_manual("Maximum Constraint Size", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  scale_x_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  scale_y_continuous(
    trans = "log",
    breaks = c(0.01, 0.03, 0.1, 0.3, 1.0),
    labels = c(0, 0.03, 0.1, 0.3, 1.0)
  ) +
  ggtitle("B") +
  guides(color = "none")
p2

p_top <- (p1 + p2) + plot_layout(guides = "collect", axes = "collect")
p_top

pdf("pnas_fig/hwcd-inphynet-isolation.pdf", width = 11.4, height = 11.4/3)
p_top
dev.off()
```




```{r}
p <- rt_df %>%
  filter(ntaxa != 1000) %>%
  filter(m_label != "m = 100") %>%
  filter(ncores %in% c(1, 2, 4)) %>%
  ggplot(aes(x = factor(ntaxa), y = runtime, color = factor(ncores))) +
  geom_boxplot(alpha = 0.00, outliers = FALSE) +
  #geom_line(data = mean_df, aes(x = ntaxa, y = rt_mean, color = factor(ncores)), alpha = 1) +
  facet_grid(m_label ~ ils_label, scales = "free") +
  scale_color_manual("CPU Cores", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  labs(x = "Number of Taxa", y = "Runtime (hours)") +
  ggtitle("A")
p

p2 <- rt_df %>%
  filter(ntaxa == 30) %>%
  filter(ncores %in% c(1, 2, 4)) %>%
  mutate(
    method = if_else(m == 10, "InPhyNet m=10", if_else(m == 20, "InPhyNet m=20", "SNaQ"))
  ) %>%
  ggplot(aes(x = method, y = runtime, color = factor(ncores))) +
  geom_boxplot() +
  labs(x = "Method") +
  scale_color_manual("CPU Cores", values = c('#1b9e77', '#d95f02', '#7570b3', "#e7298a")) +
  labs(y = "Runtime (hours)") +
  ggtitle("B")
p2

(p & guides(color = "none")) + p2 + plot_layout(widths = c(2, 2), guides = "collect", axes = "collect")

pdf("pnas_fig/runtimes.pdf", width=11.5, height=11.5/3)
(p & guides(color = "none")) + p2 + plot_layout(widths = c(2, 2), guides = "collect", axes = "collect")
dev.off()
```


