---
title: "Other Methods"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(reshape2)
theme_set(theme_bw())

split_df <- read.csv("../other-methods/comparison.csv") %>%
  melt(id = c("ntaxa", "rep", "ils", "ngt")) %>%
  mutate(
    ils_label = paste0(str_to_title(ils), " ILS"),
    ntaxa_label = factor(
      paste0(ntaxa, " taxa"),
      levels = paste0(sort(unique(ntaxa)), " taxa")
    ),
    ngt_label = factor(
      paste0(ngt, " gt"),
      levels = paste0(sort(unique(ngt)), " gt")
    ),
    method = str_sub(variable, 1, str_length(variable) - 5),
    normalized_hwcd = value,
    ils_label = factor(ils_label, levels = c("Low ILS", "High ILS"))
  ) %>%
  filter(method != "nj") %>%
  mutate(normalized_hwcd = if_else(normalized_hwcd == -1, NA, normalized_hwcd)) %>%
  filter(!is.na(normalized_hwcd))
nrow(split_df)
```




```{r}
p1 <- split_df %>%
  mutate(
    method = factor(method,
                    levels = c("neighbor", "consensus", "mnet10", "mnet20"),
                    labels = c("Consensus Network", "NeighborNet", "InPhyNet m=10", "InPhyNet m=20"))
  ) %>%
  ggplot(aes(x = ils, y = normalized_hwcd, fill = factor(method))) +
  geom_boxplot() +
  scale_x_discrete(
    "",
    limits = c("low", "high"),
    labels = c("Low ILS", "High ILS")
  ) +
  scale_y_continuous(
    "Normalized HWCD",
    limits = c(0, 1)
  ) +
  scale_fill_manual(
    "Method",
    values = c('#d95f02', '#1b9e77', '#7570b3', "#e7298a", "#66a61e", "#e6ab02")
  )
p1

pdf("fig/other-methods.pdf", width = 8, height = 4)
p1
dev.off()
```


```{r}
# This df is from snaq.Rmd
p2 <- df %>%
  mutate(ils = "Low ILS") %>%
  ggplot(aes(x = factor(m), fill = factor(m), y = approx_norm_hwcd)) +
  geom_boxplot() +
  geom_jitter(width = 0.25, height = 0)
p2
```

















