---
title: "Perfect Data Simulations"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
theme_set(theme_bw())

df <- read.csv("/mnt/dv/wid/projects4/SolisLemus-network-merging/InPhyNet-Simulations/perfect-sims/out.csv") %>%
  mutate(
    ils_label = paste0(str_to_title(ils), " ILS"),
    m_label = paste0("m = ", m),
    ntaxa_factor = factor(ntaxa, levels = sort(unique(ntaxa))),
    ntaxa_label = factor(
      paste0(ntaxa, " taxa"),
      levels = paste0(sort(unique(ntaxa)), " taxa")
    )
  )
nrow(df)
```


```{r}
p <- df %>%
  mutate(
    result = if_else(unrooted_hwcd == 0, "perfect", 
                     if_else(unrooted_hwcd/(2*ntaxa-6+2*nretic_true) <= 0.01 | unrooted_hwcd <= 4, "<1% error",
                             if_else(unrooted_hwcd / (2*ntaxa-6+2*nretic_true) <= 0.05, "1-5% error", ">5% error"))),
    result = ordered(
      result,
      levels=rev(c("perfect", "<1% error", "1-5% error", "misplaced-retics", ">5% error")),
      labels=rev(c("Perfect", "<1% error", "1-5% error", "Misplaced reticulations", ">5% error"))
    ),
    ils_label = factor(ils_label, levels = c("Low ILS", "High ILS"))
  ) %>%
  group_by(ntaxa_factor, ils_label, m_label) %>%
  mutate(
    count = n()
  ) %>%
  ungroup() %>%
  group_by(ntaxa_factor, ils_label, m_label, result) %>%
  summarise(pct = n() / first(count)) %>%
  ggplot(aes(x = ntaxa_factor, y = pct, fill = result)) +
    geom_bar(stat = "identity", position = "stack", color = "black", linewidth = 0.3) +
    facet_grid(ils_label ~ m_label) +
    labs(
      x = "Number of Taxa",
      y = "Proportion",
      fill = "Result"
    ) +
  scale_fill_manual("Result", values = c(">5% error" = '#d95f02', "1-5% error" = "#e7298a", "<1% error" = '#1b9e77', "Perfect" = '#7570b3'))
p

pdf("fig/perfect-results.pdf", width = 9, height = 4)
p
dev.off()
```


```{r}
p <- df %>%
  filter(m_label == "m = 20" & ils_label == "Low ILS") %>%
  mutate(
    result = if_else(unrooted_hwcd == 0, "perfect", 
                     if_else(unrooted_hwcd/(2*ntaxa-6+2*nretic_true) <= 0.01 | unrooted_hwcd <= 4, "<1% error",
                             if_else(unrooted_hwcd / (2*ntaxa-6+2*nretic_true) <= 0.05, "1-5% error", ">5% error"))),
    result = ordered(
      result,
      levels=rev(c("perfect", "<1% error", "1-5% error", "misplaced-retics", ">5% error")),
      labels=rev(c("Perfect", "<1% error", "1-5% error", "Misplaced reticulations", ">5% error"))
    ),
    ils_label = factor(ils_label, levels = c("Low ILS", "High ILS"))
  ) %>%
  group_by(ntaxa_factor, ils_label, nretic_true) %>%
  mutate(
    count = n()
  ) %>%
  ungroup() %>%
  group_by(ntaxa_factor, ils_label, nretic_true, result) %>%
  summarise(pct = n() / first(count)) %>%
  ggplot(aes(x = factor(nretic_true), y = pct, fill = result)) +
    geom_bar(stat = "identity", position = "stack", color = "black", linewidth = 0.3) +
    facet_grid(ntaxa_factor ~ .) +
    labs(
      x = "Number of Taxa",
      y = "Proportion",
      fill = "Result",
      title = "m = 20, low ILS"
    ) +
  scale_fill_manual("Result", values = c(">5% error" = '#d95f02', "1-5% error" = "#e7298a", "<1% error" = '#1b9e77', "Perfect" = '#7570b3'))
p
```

