universe = vanilla

error = /mnt/dv/wid/projects4/SolisLemus-network-merging/InPhyNet-Simulations/est-gts/condor/dags/n$(NTAXA)/$(ILS)-$(NGT)gt-$(M)m/rep$(REP)/err/4.err
output = /mnt/dv/wid/projects4/SolisLemus-network-merging/InPhyNet-Simulations/est-gts/condor/dags/n$(NTAXA)/$(ILS)-$(NGT)gt-$(M)m/rep$(REP)/out/4.out


executable = $(SCRIPT_DIR)/4_astral.sh
arguments = $(BASE_ARGS)

periodic_release = True

request_cpus = 1
request_memory = 16GB
request_disk = 1GB
queue
